sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "6"
  - "8"
  - "10"
deploy:
  provider: npm
  email: infrastructure@bluedrop.com
  api_key:
    secure: "TSxzZ8rv5DRD75dsKUJ/WYyzFi45jbnRwn+EPDir+TZHiKO43lyTxHY6ZooZbigrpOEqeyJc7nMm7u1nxyz2ffY4U7MfqitspVrA0753NaZzXQPL5NmEjT8Ao63ShbLn2zJdUpQI0hJMfF8QkBK7QTFCtV5NQdWRbBiGY+ZPYKt0jKXJo39Ju0INN2/b4g4Rbi3BsziG96im+61ci4JeFP/9E7StQhRnHZxW1XI2pKa8TFfQzMvcYLVEcvPonyIqeiMiRhoSOncyDFue4WRZz1n+we0G3f/+8euqRcLmj6broQUXK/rBF132pi3ESo+Za3arpcFqfpd2vtxHwu+NuyWMh4DB1a9clWDYTzVTu82Ui114DCL4SSRcrW/3cb88nsTRGXKQgwz3qfrSYyoiTTObK75aEmqcfePZCLPFjeOgm8mhd7vrsgwe+MdynsJxvGmwr0hX4cRcMfy1NX7BgOJCgPVCdadee6Hov9vB8A6F6VwyEycsM3/MUCswE7lghZgymz46e2CzdOk9TXISq+A3mrRPV6wl+aAE7drbfyPpbY22qcLwRn9xMLeBIgKAobhcuQR2JwO++SH0NBboKV8M2xUSNZ94OcOGHOKqj9kx+KYkStHOLkhJTKFKAeZBBw81NYPDdJ9eJ7tWT1t7LhBA2zBamGaYg/zKuxHh1AI="
  on:
    node: "8"
    tags: true
    repo: CoursePark/eslint-config-bluedrop
