sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "6"
  - "8"
  - "10"
deploy:
  provider: npm
  email: dev@coursepark.com
  api_key:
    secure: "N4D12fECoCSS0rN5x+X+1aM+6A0jK7Xl1+yjqKVowfVV3APwhLehIgfIqdodw5pnFJkaVOJIBvshDomCy//wFjNFeIq9f0I41ZV7Z6v5aK7rIepCo8IzhClhif7HljjAIYqfRMKuz0XtMToNGnPhp2xxc+I5Ww3BVakeR8XzDsyXWi5tXwg6V5BLX5GPrMa9k4NjsFKiOWcufgutJPu8O/LqmYsAVZ9QpeBvRQlx6oDAANyBb8E/VECTcQ36EEFiXsQO7Z04FdEVDXTRjOuOUhAxMV2bz3HWoU+b1Va8Pn2tlTlLYKUhr5vp7af2PnCbWHL3BZ8ZgKsUTtjib12SDESE+cEmoRfiKXZHUH6Hqfm+UhX4bwUTVMPANl1VnwMOGnwLyDjF9DMcFkH5+F/LfcswdmQAsgDqvcezbGP7Ob3pbdrGICaEoR0bc6rikALsoWZOgIzy6toZLCcLghD4MCwCw/wBFSWGUJNXX6Iml/yffiBvOFp9Ue81Z6iW17BekZFoS9tEakOO2T1eRGUNTYdhVVx99yFMyX1c3gbeo/gpUVZKZm0+fbF2LkvI0p3L/ID7C5tIxVJpsU3xj02Mh9wiuPlpkq1FWJ+Aj/Eh/BMmJgBouHbtyJgUbCC5NRphufFuFb8W5GdLEh+JxGPUENhriYdr95HaxUSCgpPse68="
  on:
    tags: true
    repo: CoursePark/eslint-config-bluedrop
